Repository gdg-hongik-univ/wow-class, pull requests merged in 2024-08, with the labels that each got.

#3 [Feature] 프로젝트 초기 세팅
  .github/CODEOWNERS
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .npmrc
  .prettierignore
  .prettierrc
  .vscode/settings.json
  README.md
  apps/admin/.eslintrc.js
  apps/admin/.gitignore
  apps/admin/README.md
  apps/admin/app/fonts/GeistMonoVF.woff
  apps/admin/app/fonts/GeistVF.woff
  apps/admin/app/layout.tsx
  apps/admin/app/page.tsx
  apps/admin/next.config.mjs
  apps/admin/package.json
  apps/admin/tsconfig.json
  apps/client/.eslintrc.js
  apps/client/.gitignore
  apps/client/README.md
  apps/client/app/fonts/GeistMonoVF.woff
  apps/client/app/fonts/GeistVF.woff
  apps/client/app/layout.tsx
  apps/client/app/page.tsx
  apps/client/next.config.mjs
  apps/client/package.json
  apps/client/tsconfig.json
  package.json
  packages/eslint-config/basic.js
  packages/eslint-config/next.js
  packages/eslint-config/package.json
  packages/typescript-config/basic.json
  packages/typescript-config/next.json
  packages/typescript-config/package.json
  packages/ui/.eslintrc.js
  packages/ui/package.json
  packages/ui/src/components/Modal/index.tsx
  packages/ui/tsconfig.json
  packages/ui/turbo/generators/config.ts
  packages/ui/turbo/generators/templates/component.hbs
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: 👩‍💻 리뷰 남겨주세요!

#11 [Feature] jotai 세팅
  apps/admin/app/layout.tsx
  apps/admin/components/JotaiProvider.tsx
  apps/admin/package.json
  apps/client/app/layout.tsx
  apps/client/components/JotaiProvider.tsx
  apps/client/package.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!

#14 [Feature]: CI/CD 추가
  .github/workflows/auto_assign.yml
  .github/workflows/build.yml
Labels: 👩‍💻 리뷰 남겨주세요!

#13 [Feature] fetch 클래스 및 테스트 코드 작성
  apps/admin/package.json
  apps/client/package.json
  apps/client/tsconfig.json
  packages/eslint-config/basic.js
  packages/utils/.eslintrc.js
  packages/utils/jest.config.cjs
  packages/utils/jest.setup.ts
  packages/utils/package.json
  packages/utils/src/fetcher/fetcher.test.ts
  packages/utils/src/fetcher/fetcher.ts
  packages/utils/tsconfig.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!

#18 [Feature] Text 컴포넌트 구현
  apps/admin/app/layout.tsx
  apps/admin/app/page.tsx
  apps/client/app/layout.tsx
  package.json
  packages/panda-config/common-config.ts
  packages/ui/src/components/NavItem/NavItem.stories.tsx
  packages/ui/src/components/NavItem/index.tsx
  packages/ui/src/components/Text/Text.stories.tsx
  packages/ui/src/components/Text/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/styles.css
  packages/utils/package.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!

#24 [Feat] 수강신청 페이지 & 내 과제 페이지 마크업
  apps/admin/styled-system/tokens/index.js
  apps/admin/styled-system/tokens/tokens.d.ts
  apps/admin/styled-system/types/prop-type.d.ts
  apps/client/app/(afterLogin)/layout.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/HomeworkHistory.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/HomeworkOverviewBox.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/index.ts
  apps/client/app/(afterLogin)/my-study/my-homework/page.tsx
  apps/client/app/(afterLogin)/study-apply/page.tsx
  apps/client/public/images/dot.svg
  apps/client/styled-system/tokens/index.js
  apps/client/styled-system/tokens/tokens.d.ts
  apps/client/styled-system/types/prop-type.d.ts
  package.json
  packages/eslint-config/basic.js
  packages/panda-config/package.json
  packages/ui/src/components/NavItem/NavItem.stories.tsx
  packages/ui/src/components/Space/index.tsx
  packages/ui/src/components/Table/Table.stories.tsx
  packages/ui/src/components/Table/index.tsx
  packages/ui/src/components/Text/Text.stories.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/styles.css
  packages/ui/styled-system/tokens/index.js
  packages/ui/styled-system/tokens/tokens.d.ts
  packages/ui/styled-system/types/prop-type.d.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#21 [Feature]: 스터디 개설 페이지 레이아웃
  .vscode/settings.json
  apps/admin/apis/auth/dashboardApi.ts
  apps/admin/app/error.tsx
  apps/admin/app/layout.tsx
  apps/admin/app/not-found.tsx
  apps/admin/app/studies/create-study/_components/CreateStudyButton.tsx
  apps/admin/app/studies/create-study/page.tsx
  apps/admin/app/studies/layout.tsx
  apps/admin/app/studies/page.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/constants/apiPath.ts
  apps/admin/constants/tags.ts
  apps/admin/middleware.ts
  apps/admin/types/dtos/auth.ts
  apps/admin/types/entities/auth.ts
  apps/admin/types/role.ts
  apps/admin/types/status.ts
  apps/admin/types/user.ts
  apps/admin/utils/isAdmin.ts
  package.json
  packages/utils/package.json
  packages/utils/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#31 [Feature] 스터디 수강신청 api 연결
  .github/workflows/build.yml
  apps/admin/apis/auth/dashboardApi.ts
  apps/admin/middleware.ts
  apps/client/apis/dashboardApi.ts
  apps/client/apis/studyApplyApi.ts
  apps/client/app/(afterLogin)/my-study/my-homework/_components/HomeworkHistory.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/app/(afterLogin)/study-apply/_components/index.ts
  apps/client/app/(afterLogin)/study-apply/page.tsx
  apps/client/app/error.tsx
  apps/client/constants/apiPath.ts
  apps/client/constants/dayToKorean.ts
  apps/client/constants/tags.ts
  apps/client/types/dtos/apply-study.ts
  package.json
  packages/ui/src/components/Table/Table.stories.tsx
  packages/ui/src/components/Table/index.tsx
  packages/ui/src/styles.css
  packages/utils/package.json
  packages/utils/src/fetcher/index.ts
  packages/utils/src/formatDate.ts
  packages/utils/src/formatTime.ts
  packages/utils/src/index.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#25 [Feature] 모달 컴포넌트
  apps/admin/app/@modal/(.)participants/page.tsx
  apps/admin/app/@modal/default.tsx
  apps/admin/app/layout.tsx
  packages/ui/package.json
  packages/ui/src/assets/images/close.svg
  packages/ui/src/components/Modal/Modal.stories.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/components/index.ts
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useClickOutside.ts
  packages/ui/src/hooks/useModalRoute.ts
  packages/ui/src/hooks/useModalState.ts
  packages/ui/src/styles.css
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!

#34 [Feature] 내 과제 페이지 api 연동
  apps/client/apis/studyApplyApi.ts
  apps/client/apis/studyDetailApi.ts
  apps/client/apis/studyHistoryApi.ts
  apps/client/app/(afterLogin)/layout.tsx
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmenBoxButtons.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxTitle.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmetBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/index.ts
  apps/client/app/(afterLogin)/my-study/my-assignment/page.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/HomeworkHistory.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/HomeworkOverviewBox.tsx
  apps/client/app/(afterLogin)/my-study/my-homework/_components/index.ts
  apps/client/app/(afterLogin)/my-study/my-homework/page.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/constants/apiPath.ts
  apps/client/constants/assignmentMockData.ts
  apps/client/constants/assignmentSubmissionStatusMap.ts
  apps/client/constants/tags.ts
  apps/client/public/images/empty-history.png
  apps/client/types/dtos/applyStudy.ts
  apps/client/types/dtos/auth.ts
  apps/client/types/dtos/studyDetail.ts
  apps/client/types/dtos/studyHistory.ts
  apps/client/types/entities/common/assignment.ts
  apps/client/types/entities/common/auth.ts
  apps/client/types/entities/myAssignment.ts
  apps/client/types/entities/myStudy.ts
  apps/client/utils/index.ts
  apps/client/utils/isDeadlinePassed.ts
  packages/ui/src/styles.css
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#39 [Feature] 나의 스터디 페이지 모달 구현
  apps/client/app/(afterLogin)/my-study/@modal/(.)attendance-check/page.tsx
  apps/client/app/(afterLogin)/my-study/@modal/default.tsx
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/AttendanceStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/app/(afterLogin)/my-study/attendance-check/page.tsx
  apps/client/app/(afterLogin)/my-study/default.tsx
  apps/client/app/(afterLogin)/my-study/layout.tsx
  apps/client/components/LinkButton.tsx
  apps/client/constants/routePath.ts
  apps/client/package.json
  packages/ui/.storybook/preview.ts
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/styles.css
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#30 [Feature]: 스터디 개설하기 api 연동
  apps/admin/apis/form/createStudyApi.ts
  apps/admin/app/layout.tsx
  apps/admin/app/studies/[study]/_components/Header.tsx
  apps/admin/app/studies/[study]/page.tsx
  apps/admin/app/studies/create-study/_components/CreateStudyButton.tsx
  apps/admin/app/studies/create-study/_components/StudyMentorSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyNameTextField.tsx
  apps/admin/app/studies/create-study/_components/index.ts
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyCourseSelect.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyDayOfWeekSelect.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyFormatSelect.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudySemesterSelect.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyStartDatePick.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/StudyTime.tsx
  apps/admin/app/studies/create-study/_components/studyBasicInfo/index.tsx
  apps/admin/app/studies/create-study/page.tsx
  apps/admin/constants/apiPath.ts
  apps/admin/constants/dayToKorean.ts
  apps/admin/constants/mockData.ts
  apps/admin/constants/router/study.ts
  apps/admin/hooks/useClickOutSide.tsx
  apps/admin/package.json
  apps/admin/types/dtos/createStudy.ts
  apps/admin/types/entities/study.ts
  packages/ui/src/styles.css
  packages/utils/src/formatDate.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#45 [Feature] 수강신청 페이지 모달 플로우 추가
  apps/client/apis/studyApplyApi.ts
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmenBoxButtons.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxTitle.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmetBoxInfo.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentHistory/index.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/index.ts
  apps/client/app/(afterLogin)/my-assignment/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-application/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-cancellation/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/default.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/app/(afterLogin)/study-apply/default.tsx
  apps/client/app/(afterLogin)/study-apply/layout.tsx
  apps/client/app/(afterLogin)/study-apply/page.tsx
  apps/client/app/(afterLogin)/study-apply/study-application/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/study-cancellation/[studyId]/page.tsx
  apps/client/constants/routePath.ts
  apps/client/middleware.ts
  apps/client/types/dtos/applyStudy.ts
  apps/client/types/entities/common/study.ts
  apps/client/types/entities/common/time.ts
  apps/client/utils/revalidateTagByName.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#47 [Feature] 과제 제출 api 연동
  apps/client/apis/studyHistoryApi.ts
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmenBoxButtons.tsx
  apps/client/constants/assignmentMockData.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#37 [Feature] : 개설된 스터디 보기 api 연동
  apps/admin/apis/study/createStudyApi.ts
  apps/admin/app/studies/[study]/_components/Header.tsx
  apps/admin/app/studies/_components/StudyList.tsx
  apps/admin/app/studies/_components/StudyListItem.tsx
  apps/admin/app/studies/detail-info/[studyId]/page.tsx
  apps/admin/app/studies/layout.tsx
  apps/admin/app/studies/page.tsx
  apps/admin/constants/apiPath.ts
  apps/admin/constants/router/routerPath.ts
  apps/admin/constants/tags.ts
  apps/admin/public/images/empty.svg
  apps/admin/types/dtos/createStudy.ts
  apps/admin/types/dtos/studyList.ts
  apps/admin/types/entities/dayofweek.ts
  apps/admin/types/entities/study.ts
  apps/admin/types/entities/time.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#46 [Feature] 레포지토리 입력할 때 모달 플로우 추가
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmenBoxButtons.tsx
  apps/client/app/(afterLogin)/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/(.)repository-url/confirmation/page.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/(.)repository-url/default.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/default.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxButtons.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxTitle.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/EmptyAssignmentBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/index.ts
  apps/client/app/(afterLogin)/my-study/my-assignment/default.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/layout.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/page.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/repository-url/confirmation/page.tsx
  apps/client/constants/assignmentMockData.ts
  apps/client/constants/routePath.ts
  apps/client/hooks/useMatchedStudyHistoryId.ts
  apps/client/middleware.ts
  apps/client/types/dtos/studyHistory.ts
  apps/client/types/entities/myAssignment.ts
  packages/ui/src/styles.css
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#49 [Feat] 나의 과제 페이지 Tooltip, Popover 컴포넌트 구현
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentDescription.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHeader.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/page.tsx
  apps/client/components/Popover.tsx
  apps/client/components/Tooltip.tsx
  apps/client/constants/assignmentMockData.ts
  packages/ui/src/components/Modal/Modal.stories.tsx
  packages/ui/src/components/Modal/index.tsx
  packages/ui/src/hooks/index.ts
  packages/ui/src/hooks/useModalState.ts
  packages/ui/src/hooks/useOpenState.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#41 [Refactor] 나의 스터디 페이지 클라이언트 컴포넌트 서버 컴포넌트로 변경
  apps/client/app/(afterLogin)/my-study/page.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-after-recruitment/page.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-during-recruitment/page.tsx
  apps/client/app/(beforeLogin)/auth/_components/LoginButton.tsx
  apps/client/app/(beforeLogin)/auth/page.tsx
  apps/client/app/(beforeLogin)/landing/page.tsx
  apps/client/constants/routePath.ts
  package.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#67 [Fix] 프로덕션/개발 환경 구분 환경 변수 VERCEL_ENV로 변경
  apps/admin/middleware.ts
  apps/client/constants/environment.ts
  packages/utils/src/fetcher/index.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트, ⛏어드민

#58 [Feature] 내비게이션 바 역할에 따라 멘토 페이지 전환 버튼 보여주기 여부 조정
  apps/client/apis/dashboardApi.ts
  apps/client/components/Navbar.tsx
  apps/client/constants/navMenu.ts
  apps/client/constants/routePath.ts
  apps/client/middleware.ts
  apps/client/types/dtos/auth.ts
  packages/ui/src/components/NavItem/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#60 [Feature] 클라이언트 페이지 메타데이터 추가
  apps/client/app/(afterLogin)/layout.tsx
  apps/client/app/(afterLogin)/my-page/layout.tsx
  apps/client/app/(afterLogin)/my-study/layout.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/layout.tsx
  apps/client/app/(afterLogin)/study-apply/layout.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-after-recruitment/page.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-during-recruitment/page.tsx
  apps/client/app/(beforeLogin)/social-login/redirect/page.tsx
  apps/client/app/layout.tsx
  apps/client/public/images/og-image.svg
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#44 [Feature] 나의 스터디 페이지 api 연결
  apps/client/apis/myStudyApi.ts
  apps/client/apis/studyApplyApi.ts
  apps/client/app/(afterLogin)/my-study/@modal/(.)attendance-check/page.tsx
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/AttendanceStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTasks.tsx
  apps/client/app/(afterLogin)/my-study/_components/EmptyStudy.tsx
  apps/client/app/(afterLogin)/my-study/_components/Header.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyAnnouncementList.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/app/(afterLogin)/my-study/_components/index.ts
  apps/client/app/(afterLogin)/my-study/layout.tsx
  apps/client/app/(afterLogin)/my-study/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-application/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-cancellation/[studyId]/page.tsx
  apps/client/constants/apiPath.ts
  apps/client/constants/attendanceStatusMap.ts
  apps/client/constants/mockData.ts
  apps/client/constants/routePath.ts
  apps/client/constants/tags.ts
  apps/client/hooks/useFetchAttendanceCheckModalInfoData.ts
  apps/client/hooks/useFetchBasicStudyInfoData.ts
  apps/client/public/images/empty.svg
  apps/client/types/dtos/applyStudy.ts
  apps/client/types/dtos/myStudy.ts
  apps/client/types/entities/common/time.ts
  apps/client/types/entities/myStudy.ts
  apps/client/utils/getIsCurrentWeek.ts
  apps/client/utils/validateAttendanceNumber.ts
  packages/utils/src/formatDate.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#48 [Feature] 스터디 공지 수정, 삭제, 작성
  apps/admin/apis/auth/dashboardApi.ts
  apps/admin/apis/study/studyInfoApi.ts
  apps/admin/app/layout.tsx
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-delete/page.tsx
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-modify/page.tsx
  apps/admin/app/studies/[studyId]/@modal/default.tsx
  apps/admin/app/studies/[studyId]/_components/announcement/CreateStudyAnnouncement.tsx
  apps/admin/app/studies/[studyId]/_components/announcement/StudyAnnouncement.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/CancelStudyButton.tsx
  apps/admin/app/studies/[studyId]/_components/header/Header.tsx
  apps/admin/app/studies/[studyId]/_components/session/SessionListItem.tsx
  apps/admin/app/studies/[studyId]/announcement-delete/page.tsx
  apps/admin/app/studies/[studyId]/announcement-modify/page.tsx
  apps/admin/app/studies/[studyId]/default.tsx
  apps/admin/app/studies/[studyId]/layout.tsx
  apps/admin/app/studies/[studyId]/page.tsx
  apps/admin/app/studies/create-study/_components/CreateStudyButton.tsx
  apps/admin/app/studies/layout.tsx
  apps/admin/app/studies/page.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/constants/apiPath.ts
  apps/admin/constants/router/study.ts
  apps/admin/constants/tags.ts
  apps/admin/types/dtos/announcement.ts
  apps/admin/types/dtos/assignmentList.ts
  apps/admin/types/dtos/sessionList.ts
  apps/admin/types/dtos/studyList.ts
  apps/admin/types/entities/assignStatus.ts
  apps/admin/types/entities/difficulty.ts
  apps/admin/types/entities/study.ts
  apps/admin/utils/checkThisWeek.ts
  apps/client/package.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#71 [Design] 클라이언트 페이지 디자인 및 수정 사항 반영
  apps/admin/app/error.tsx
  apps/admin/app/not-found.tsx
  apps/client/app/(afterLogin)/layout.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-after-recruitment/page.tsx
  apps/client/app/(beforeLogin)/(auth-error)/auth-error-during-recruitment/page.tsx
  apps/client/app/(beforeLogin)/auth/page.tsx
  apps/client/app/(beforeLogin)/landing/page.tsx
  apps/client/app/error.tsx
  apps/client/app/not-found.tsx
  apps/client/components/Navbar.tsx
  apps/client/constants/navMenu.ts
  packages/ui/src/components/NavItem/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#74 [Chore] 클라이언트 스터디 커리큘럼 api 엔드 포인트 및 dto 변경사항 반영
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/constants/apiPath.ts
  apps/client/types/dtos/myStudy.ts
  apps/client/types/entities/common/study.ts
  apps/client/types/entities/myStudy.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#82 [Fix] 수강신청 페이지 과제 스터디의 경우
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/types/dtos/applyStudy.ts
Labels: 📝클라이언트

#72 [Feature] 스터디 생성 모달 창을 만들고, 스터디 생성 관련 예외처리를 진행해요.
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-delete/page.tsx
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-modify/page.tsx
  apps/admin/app/studies/_components/StudyListItem.tsx
  apps/admin/app/studies/create-study/@modal/(.)created-study-check/page.tsx
  apps/admin/app/studies/create-study/@modal/default.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyCourseSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyDayOfWeekSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyFormatSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudySemesterSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyTime.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/index.tsx
  apps/admin/app/studies/create-study/_components/index.ts
  apps/admin/app/studies/create-study/created-study-check/page.tsx
  apps/admin/app/studies/create-study/default.tsx
  apps/admin/app/studies/create-study/layout.tsx
  apps/admin/app/studies/create-study/page.tsx
  apps/admin/constants/router/routerPath.ts
  apps/admin/hooks/useParseSearchParams.ts
  apps/admin/types/dtos/createStudy.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#77 [Bug] 스터디 개설 validation 처리, querystring 사용 방식 개선
  apps/admin/app/studies/[studyId]/_components/header/Header.tsx
  apps/admin/app/studies/create-study/@modal/(.)created-study-check/page.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyDayOfWeekSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudySemesterSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyTime.tsx
  apps/admin/app/studies/create-study/page.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#88 [Chore] 클라이언트 페이지 성능 최적화
  apps/client/app/(afterLogin)/my-page/@modal/(.)logout/page.tsx
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/Header.tsx
  apps/client/app/api/my-page/logout/route.ts
  apps/client/components/Navbar.tsx
  apps/client/constants/cookieKey.ts
  apps/client/middleware.ts
  apps/client/types/dtos/myStudy.ts
  packages/fonts/ProductSans-Bold.woff
  packages/fonts/ProductSans-Bold.woff2
  packages/fonts/ProductSans-Regular.woff
  packages/fonts/ProductSans-Regular.woff2
  packages/fonts/SUIT-Bold.woff
  packages/fonts/SUIT-Bold.woff2
  packages/fonts/SUIT-ExtraBold.woff
  packages/fonts/SUIT-ExtraBold.woff2
  packages/fonts/SUIT-ExtraLight.woff
  packages/fonts/SUIT-ExtraLight.woff2
  packages/fonts/SUIT-Heavy.woff
  packages/fonts/SUIT-Heavy.woff2
  packages/fonts/SUIT-Light.woff
  packages/fonts/SUIT-Light.woff2
  packages/fonts/SUIT-Medium.woff
  packages/fonts/SUIT-Medium.woff2
  packages/fonts/SUIT-Regular.woff
  packages/fonts/SUIT-Regular.woff2
  packages/fonts/SUIT-SemiBold.woff
  packages/fonts/SUIT-SemiBold.woff2
  packages/fonts/SUIT-Thin.woff
  packages/fonts/SUIT-Thin.woff2
  packages/fonts/index.css
  packages/ui/src/components/NavItem/index.tsx
  packages/ui/src/styles.css
  packages/utils/src/fetcher/index.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#84 [Feat] 수강 신청,마이 페이지 관련 QA 반영
  apps/client/apis/studyApplyApi.ts
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-application/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/@modal/(.)study-cancellation/[studyId]/page.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/constants/revalidateTime.ts
  apps/client/types/dtos/applyStudy.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#76 [Feature] 과제 개설, 수정, 조회 UI 및 API 연결
  apps/admin/apis/study/studyApi.ts
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentButtons.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/CancelStudyButton.tsx
  apps/admin/app/studies/[studyId]/_components/header/Header.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentForm.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentHeader.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/CustomTextField.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/SuccessModal.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/edit-assignment/page.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/page.tsx
  apps/admin/app/studies/assignments/layout.tsx
  apps/admin/app/studies/create-study/@modal/(.)created-study-check/page.tsx
  apps/admin/components/ItemSeparator.tsx
  apps/admin/constants/assignmentStatusMap.ts
  apps/admin/constants/router/routerPath.ts
  apps/admin/package.json
  apps/admin/types/dtos/assignmentList.ts
  apps/admin/types/entities/assignment.ts
  packages/ui/src/components/Modal/index.tsx
  pnpm-lock.yaml
Labels: ⛏어드민

#91 [Feature] 어드민 페이지 메타데이터 설정 및 UX 개선
  apps/admin/app/layout.tsx
  apps/admin/app/studies/[studyId]/layout.tsx
  apps/admin/app/studies/[studyId]/page.tsx
  apps/admin/app/studies/create-study/layout.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/CreateStudyDetailInfo.tsx
  apps/admin/app/studies/detail-info/[studyId]/layout.tsx
  apps/admin/app/studies/detail-info/[studyId]/page.tsx
  apps/admin/app/studies/layout.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/public/images/og-image.png
  packages/ui/src/components/Modal/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민
