Repository gdg-hongik-univ/wow-class, pull requests merged in 2024-09, with the labels that each got.

#98 [Design] 나의 스터디 페이지 스터디 커리큘럼 반응형 디자인 적용
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/middleware.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#102 [Chore] 클라이언트 나의 스터디 페이지 및 자잘한 QA 사항 반영
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTaskItem.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTasks.tsx
  apps/client/app/(afterLogin)/my-study/_components/EmptyStudy.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/app/(afterLogin)/my-study/_components/index.ts
  apps/client/app/(afterLogin)/my-study/layout.tsx
  apps/client/app/layout.tsx
  package.json
  packages/utils/src/formatDate.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#94 [Refactor] : 어드민 서비스 미들웨어 로직 추가 및 스터디 리스트 레이아웃 조정
  apps/admin/app/studies/[studyId]/layout.tsx
  apps/admin/app/studies/_components/StudyListItem.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyFormatSelect.tsx
  apps/admin/constants/cookieKey.ts
  apps/admin/constants/url.ts
  apps/admin/hooks/useForm.tsx
  apps/admin/middleware.ts
  apps/admin/types/entities/study.ts
  apps/admin/utils/setExpireTime.ts
  packages/ui/src/components/NavItem/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#105 [Feat] 수강신청 페이지 큐에이 반영
  apps/client/apis/studyApplyApi.ts
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentDescription.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/constants/revalidateTime.ts
  apps/client/types/entities/common/study.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#103 [Fix] 네비게이션 관련 QA 이슈 해결
  apps/admin/components/Navbar.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#99 [Feature] 과제 Picker 컴포넌트 도입 및 QA사항 반영
  apps/admin/app/layout.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentButtons.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentList.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx
  apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentForm.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/edit-assignment/page.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/page.tsx
  apps/admin/types/dtos/assignmentList.ts
  apps/admin/utils/getIsCurrentWeek.ts
  package.json
  packages/utils/src/formatDate.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#106 [Fix] 스터디 상세, 스터디 생성 관련 QA 이슈 해결
  apps/admin/app/studies/[studyId]/_components/header/Header.tsx
  apps/admin/app/studies/[studyId]/page.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyTime.tsx
  apps/admin/app/studies/create-study/_components/StudyMentorSelect.tsx
  apps/admin/app/studies/detail-info/[studyId]/@modal/(.)detail-Info-check/_hooks/useSubmitStudyDetailInfo.ts
  apps/admin/app/studies/detail-info/[studyId]/@modal/(.)detail-Info-check/page.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/CreateStudyDetailInfo.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyDescription.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyInfoDifficulty.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyInfoStatus.tsx
  apps/admin/app/studies/detail-info/[studyId]/_hooks/usePrefillStudyDetailInfo.ts
  apps/admin/app/studies/page.tsx
  apps/admin/constants/date.ts
  apps/admin/package.json
  apps/admin/types/dtos/curriculumList.ts
  apps/admin/utils/validate/studyDetailInfo.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#109 [Fix] 스터디 공지 관련 QA 이슈 해결
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-delete/page.tsx
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-modify/page.tsx
  apps/admin/app/studies/[studyId]/_components/announcement/CreateStudyAnnouncement.tsx
  apps/admin/app/studies/[studyId]/_components/announcement/StudyAnnouncement.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx
  apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
  apps/admin/app/studies/[studyId]/_components/header/Header.tsx
  apps/admin/app/studies/[studyId]/hooks/usePrefillAnnouncement.ts
  apps/admin/app/studies/_components/StudyListItem.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyNameTextField.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyTextInfo.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#111 [Feature] 스터디 멘토 검색 기능 추가
  apps/admin/apis/study/createStudyApi.ts
  apps/admin/app/studies/create-study/_components/StudyMentorSelect.tsx
  apps/admin/constants/apiPath.ts
  apps/admin/constants/tags.ts
  apps/admin/types/dtos/searchStudyMentor.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#116 [Chore] 나의 스터디 페이지 QA 반영
  apps/client/app/(afterLogin)/my-study/@modal/(.)attendance-check/page.tsx
  apps/client/app/(afterLogin)/my-study/_components/AttendanceStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTasks.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyAnnouncementList.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/hooks/useFetchAttendanceCheckModalInfoData.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#118 [Fix] 과제, 출결 관련 QA 반영
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx
  apps/admin/app/studies/[studyId]/_components/attendance/AttendanceItem.tsx
  apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentHeader.tsx
  apps/admin/utils/getIsToday.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#119 [Fix] 자잘한 UI 수정 및 개설 강의 상태 NONE에서 OPEN으로 변경, QA 반영
  apps/admin/app/studies/[studyId]/@modal/(.)announcement-modify/page.tsx
  apps/admin/app/studies/[studyId]/_components/announcement/CreateStudyAnnouncement.tsx
  apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
  apps/admin/app/studies/[studyId]/page.tsx
  apps/admin/app/studies/_components/StudyListItem.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyCourseSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyDayOfWeekSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyFormatSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudySemesterSelect.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyTime.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/index.tsx
  apps/admin/app/studies/create-study/_components/StudyMentorSelect.tsx
  apps/admin/app/studies/create-study/page.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyInfoBox/StudyInfoStatus.tsx
  apps/admin/app/studies/detail-info/[studyId]/_hooks/usePrefillStudyDetailInfo.ts
  apps/admin/hooks/useResizeTextarea.ts
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#123 [Hotfix] 스터디 커리큘럼 12주로 연장, 스터디 신청 기간 자유롭게 선택 가능하도록 수정
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyApplyDatePick.tsx
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyCourseSelect.tsx
  apps/admin/constants/date.ts
  apps/admin/constants/studyCurriculum.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#114 [Refactor] 과제 api 연결 및 바뀐 dto 반영
  apps/client/apis/studyDetailApi.ts
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/(.)repository-url/confirmation/page.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/(.)repository-url/default.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/@modal/default.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxButtons.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxTitle.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/EmptyAssignmentBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentDescription.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHeader.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/layout.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/repository-url/confirmation/page.tsx
  apps/client/components/Navbar.tsx
  apps/client/components/Tooltip.tsx
  apps/client/constants/assignmentMockData.ts
  apps/client/constants/assignmentSubmissionStatusMap.ts
  apps/client/constants/navMenu.ts
  apps/client/constants/routePath.ts
  apps/client/constants/tags.ts
  apps/client/hooks/useMatchedStudyHistoryId.ts
  apps/client/types/dtos/myStudy.ts
  apps/client/types/dtos/studyDetail.ts
  apps/client/types/dtos/studyHistory.ts
  apps/client/types/entities/common/assignment.ts
  apps/client/types/entities/myAssignment.ts
  apps/client/types/entities/myStudy.ts
  apps/client/utils/getAssignmentGithubFolderName.ts
  apps/client/utils/getIsAfterStartDate.ts
  apps/client/utils/index.ts
  apps/client/utils/isDeadlinePassed.ts
  apps/client/utils/isGithubRepositoryUrl.ts
  packages/ui/src/components/NavItem/index.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#122 [Fix] 과제 종료 날짜 현재일 이후로 설정 가능하도록 수정
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentList.tsx
  apps/admin/app/studies/[studyId]/_components/assignment/AssignmentListItem.tsx
  apps/admin/app/studies/[studyId]/_components/curriculum/CurriculumListItem.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/_components/AssignmentForm.tsx
  apps/admin/app/studies/assignments/[studyDetailId]/page.tsx
  apps/admin/types/dtos/assignmentList.ts
  apps/admin/utils/getIsCurrentWeek.ts
  package.json
  pnpm-lock.yaml
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#126 [Hotfix] 스터디 상세 작성 모달창 state로 관리하도록 개선
  apps/admin/app/studies/detail-info/[studyId]/@modal/default.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/CreateStudyDetailInfo.tsx
  apps/admin/app/studies/detail-info/[studyId]/_components/StudyDetailInfoCheckModal.tsx
  apps/admin/app/studies/detail-info/[studyId]/_hooks/useSubmitStudyDetailInfo.ts
  apps/admin/app/studies/detail-info/[studyId]/default.tsx
  apps/admin/app/studies/detail-info/[studyId]/layout.tsx
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#131 [HotFix]: 과제 페이지 롤백
  apps/client/components/Navbar.tsx
  apps/client/constants/navMenu.ts
Labels: 📝클라이언트

#128 [Chore] 나의 스터디 페이지 QA 반영
  apps/client/apis/myStudyApi.ts
  apps/client/app/(afterLogin)/my-page/layout.tsx
  apps/client/app/(afterLogin)/my-study/@modal/(.)attendance-check/page.tsx
  apps/client/app/(afterLogin)/my-study/_components/AssignmentStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/AttendanceStatusBox.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTaskCarousel.tsx
  apps/client/app/(afterLogin)/my-study/_components/DailyTaskItem.tsx
  apps/client/app/(afterLogin)/my-study/_components/StudyCurriculum.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/layout.tsx
  apps/client/app/layout.tsx
  apps/client/hooks/useAttendanceCheckSearchParams.ts
  apps/client/hooks/useFetchAttendanceCheckModalInfoData.ts
  apps/client/hooks/useScrollCarouselButtonVisibility.ts
  packages/utils/src/fetcher/index.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#134 [Hotfix] 스터디 신청 기간 날짜 겹치지 않도록 수정
  apps/admin/app/studies/create-study/_components/StudyBasicInformation/StudyStartDatePick.tsx
Labels: ⛏어드민

#136 [Fix] 스터디 목록 조회를 멘토용 조회 API로 수정해요.
  apps/admin/apis/auth/dashboardApi.ts
  apps/admin/apis/study/studyApi.ts
  apps/admin/app/studies/_components/StudyList.tsx
  apps/admin/app/studies/create-study/@modal/(.)created-study-check/page.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/constants/tags.ts
  apps/admin/types/dtos/studyList.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#133 [Fix] 나의 과제 페이지, 수강 신청 페이지 QA 반영
  apps/client/apis/studyDetailApi.ts
  apps/client/apis/studyHistoryApi.ts
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxButtons.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/RepositorySubmissionBox.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/study-apply/_components/StudyItem.tsx
  apps/client/components/Navbar.tsx
  apps/client/components/Popover.tsx
  apps/client/constants/assignmentMockData.ts
  apps/client/constants/navMenu.ts
  apps/client/constants/routePath.ts
  apps/client/types/dtos/studyDetail.ts
  apps/client/types/entities/common/assignment.ts
  apps/client/utils/getAssignmentGithubFolderName.ts
  apps/client/utils/getNowIsAfterStartDate.ts
Labels: 👩‍💻 리뷰 남겨주세요!, 📝클라이언트

#144 [Fix] 과제 페이지 EmptyStudy 처리, 제출 실패 언노운 일 때 UI 수정
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/AssignmentBoxInfo.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/AssignmentOverviewBox/FailurePopover.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentContent/index.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/_components/AssignmentHistory/AssignmentHistoryItem.tsx
  apps/client/app/(afterLogin)/my-study/my-assignment/page.tsx
Labels: 📝클라이언트

#140 [Feature] 임시 스터디원 관리 UI, API 연결
  apps/admin/apis/study/studyApi.ts
  apps/admin/app/@modal/(.)participants/page.tsx
  apps/admin/app/@modal/default.tsx
  apps/admin/app/layout.tsx
  apps/admin/app/participants/page.tsx
  apps/admin/app/students/_components/StudentList.tsx
  apps/admin/app/students/_components/StudentListItem.tsx
  apps/admin/app/students/_components/StudentsHeader.tsx
  apps/admin/app/students/_components/StudyDropDown/DropDownTrigger.tsx
  apps/admin/app/students/_components/StudyDropDown/index.tsx
  apps/admin/app/students/_contexts/StudyProvider.tsx
  apps/admin/app/students/layout.tsx
  apps/admin/app/students/page.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/constants/tags.ts
  apps/admin/hooks/fetch/useFetchStudents.ts
  apps/admin/middleware.ts
  apps/admin/types/dtos/studyStudent.ts
  packages/utils/src/fetcher/index.ts
Labels: 👩‍💻 리뷰 남겨주세요!, ⛏어드민

#146 [Deploy] 임시 스터디원 관리 UI, API 연결 (#140)
  apps/admin/apis/study/studyApi.ts
  apps/admin/app/@modal/(.)participants/page.tsx
  apps/admin/app/@modal/default.tsx
  apps/admin/app/layout.tsx
  apps/admin/app/participants/page.tsx
  apps/admin/app/students/_components/StudentList.tsx
  apps/admin/app/students/_components/StudentListItem.tsx
  apps/admin/app/students/_components/StudentsHeader.tsx
  apps/admin/app/students/_components/StudyDropDown/DropDownTrigger.tsx
  apps/admin/app/students/_components/StudyDropDown/index.tsx
  apps/admin/app/students/_contexts/StudyProvider.tsx
  apps/admin/app/students/layout.tsx
  apps/admin/app/students/page.tsx
  apps/admin/components/Navbar.tsx
  apps/admin/constants/tags.ts
  apps/admin/hooks/fetch/useFetchStudents.ts
  apps/admin/middleware.ts
  apps/admin/types/dtos/studyStudent.ts
  packages/utils/src/fetcher/index.ts
Labels: ⛏어드민
